name: 'NC Data'

'on':
  push:
    branches:
      - main
    paths:
      - 'raw-data/*NC_DETECT*.csv'
  workflow_dispatch:

permissions:
  contents: 'write'

jobs:
  update:
    name: 'update'
    if: "${{ github.repository == 'ACCIDDA/flu-metrocast-nc' }}"
    runs-on: ubuntu-latest
    steps:
      - name: 'set date'
        id: 'date'
        run: |
          echo "DATE=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: 'checkout repository'
        uses: 'actions/checkout@v6'
        with:
          ref: 'main'
          fetch-depth: 0
      - name: 'setup R'
        uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true
          extra-repositories: 'https://hubverse-org.r-universe.dev'
      - name: 'update R'
        run: 'sudo apt-get update'
      - name: 'install dependencies'
        uses: 'r-lib/actions/setup-r-dependencies@v2'
        with:
          packages: |
            any::hubValidations
            any::sessioninfo
            any::magrittr
            any::dplyr
            any::tidyr
            any::purrr
            any::lubridate
            any::readr
      - name: 'run NC update script'
        run: 'Rscript ./src/NC_clean.R'
      - name: 'configure git'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: 'open pull request'
        run: |
          git add target-data/
          if git diff --cached --quiet; then
            echo "No changes in `target-data/`, nothing to commit."
            exit 0
          fi
          git commit -m "Update NC target data for $DATE"
          git push origin main
          gh pr create \
            --repo "reichlab/flu-metrocast" \
            --head "ACCIDDA:main" \
            --base main \
            --title "Update NC target data for $DATE"
        env:
          DATE: "${{ env.DATE }}"
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
